name: Build and Deploy to ide-design.labs.jb.gg

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_DEPLOY_BASE: /vcs/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy:
    needs: build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: JetBrains/sre-workflows/.github/workflows/gke-skaffold.yaml@master
    with:
      gcp_project: itk8s-208609
      gcp_region: europe-west1
      gke_cluster: europe-west1-production
      service_account: ghc-1bfd3d748e123555d7e00171d6@jetbrains-github-controller.iam.gserviceaccount.com
      workload_identity_provider: projects/1035036546488/locations/global/workloadIdentityPools/github-controller/providers/github-org-878437
      skaffold_profile: prod
      artifact_name: dist
      artifact_path: dist
